exclude_paths:
  - "src/**"

rules:
  - id: ai_high_risk
    type: ai-threshold
    severity: critical
    threshold: 0.75
    description: >
      Flags files where explainable model predicts >75% AI-likelihood.
      Intended for high scrutiny on critical or core source files.

  - id: ai_medium_risk
    type: ai-threshold
    severity: medium
    threshold: 0.55
    description: >
      Monitors moderate AI similarity. Review manually if logic or comments look machine-generated.

  # --- Security: Regex rules ---
  - id: hardcoded_secrets
    type: regex
    severity: critical
    patterns:
      - "API_KEY"
      - "SECRET"
      - "PASSWORD"
      - "PRIVATE_KEY"
      - "ACCESS_TOKEN"
      - "Bearer [A-Za-z0-9\\-_.]+"

  - id: aws_access_key
    type: regex
    severity: critical
    patterns:
      # Matches AWS access keys starting with “AKIA” or “ASIA”
      - "AKIA[0-9A-Z]{16}"
      - "ASIA[0-9A-Z]{16}"
    description: Detects hardcoded AWS access keys.

  - id: openai_api_key
    type: regex
    severity: critical
    patterns:
      # Matches OpenAI API keys starting with “sk-” followed by 32+ alphanumerics
      - "sk-[A-Za-z0-9]{32,}"
    description: Detects hardcoded OpenAI secrets.

  - id: generic_jwt
    type: regex
    severity: high
    patterns:
      # Very rough match for JWT tokens (three Base64 segments separated by dots)
      - "ey[A-Za-z0-9_-]{10,}\\.[A-Za-z0-9_-]{10,}\\.[A-Za-z0-9_-]{10,}"
    description: Detects likely JWT tokens.
    
  - id: insecure_http
    type: regex
    severity: high
    patterns:
      - "http://"

  - id: eval_or_exec
    type: regex
    severity: high
    patterns:
      - "\\beval\\("
      - "\\bexec\\("
    description: >
      Detects unsafe dynamic execution of code strings.

  # --- File existence requirements ---
  - id: require_readme
    type: file-exists
    path: README.md
    severity: low
    description: Ensures a README.md file exists in repo root.

  - id: require_license
    type: file-exists
    path: LICENSE
    severity: low

  # --- Metrics thresholds ---
  - id: line_length_limit
    type: metric
    severity: medium
    max_lines: 400
    min_lines: 5
    description: >
      Warns if files are unusually short or overly long for maintainability review.

  - id: ai_line_density
    type: metric
    severity: medium
    max_ai_percentage: 60
    description: >
      Ensures AI-generated content remains below 60% of total lines per PR.
