version: 1
rules:
  - id: ban-unsafe-import
    description: Disallow "from typing import *"
    type: regex
    languages: ["py"]
    patterns:
      - "\\bfrom\\s+typing\\s+import\\s+\\*"
    severity: medium

  - id: ban-todo-java
    description: Flag TODO comments in Java files
    type: regex
    languages: ["java"]
    patterns:
      - "TODO"
    severity: low
