name: Blackbox Audit

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to audit'
        required: true
        default: 'main'

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Get OIDC token
        id: get-token
        uses: actions/github-script@v7
        with:
          script:
            core.setOutput('jwt', await github.actions.getIdToken())
      - name: Call server
        run: |
          curl -H "Authorization: Bearer ${{ steps.get-token.outputs.jwt }}" \
               -X POST https://blackbox-labs.org/audit \
               -d "{\"repo\":\"${{ github.repository }}\", \"branch\":\"${{ github.event.inputs.branch }}\"}"
