name: Blackbox Audit

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to audit'
        required: true
        default: 'main'

permissions:
  id-token: write
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
     - name: Get OIDC token
       id: get-token
       run: |
         JWT=$(curl --fail -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                     "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value)
         echo "jwt=$JWT" >> $GITHUB_OUTPUT

     - name: Call server
       run: |
         status=$(curl -o response.txt -H "Authorization: Bearer ${{ steps.get-token.outputs.jwt }}" \
                  -X POST https://blackbox-labs.org/audit \
                  -d "{\"branch\":\"${{ github.event.inputs.branch }}\"}")
         echo "Response code: $status"
         [ "$status -eq 200 ]

